#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#ifndef CFG_TUSB_MCU
#error CFG_TUSB_MCU must be defined
#endif

#ifndef USB_MIDI_HOST
#define USB_MIDI_HOST 0
#endif

#ifndef TINYUSB_HAS_MIDI_HOST
#define TINYUSB_HAS_MIDI_HOST 0
#endif

#ifndef CFG_TUSB_OS
#define CFG_TUSB_OS OPT_OS_PICO
#endif

#ifndef CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_SECTION
#endif

#ifndef CFG_TUSB_MEM_ALIGN
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))
#endif

#if USB_MIDI_HOST

#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_HOST | OPT_MODE_FULL_SPEED)
#define CFG_TUH_ENABLED 1
#define CFG_TUD_ENABLED 0

#ifndef BOARD_TUH_RHPORT
#define BOARD_TUH_RHPORT 0
#endif

#ifndef BOARD_TUH_MAX_SPEED
#define BOARD_TUH_MAX_SPEED OPT_MODE_FULL_SPEED
#endif

#define CFG_TUH_MAX_SPEED BOARD_TUH_MAX_SPEED
#define CFG_TUH_ENUMERATION_BUFSIZE 256
#define CFG_TUH_DEVICE_MAX 1
#define CFG_TUH_HUB 0
#define CFG_TUH_CDC 0
#define CFG_TUH_CDC_FTDI 0
#define CFG_TUH_CDC_CP210X 0
#define CFG_TUH_CDC_CH34X 0
#define CFG_TUH_HID 0
#define CFG_TUH_MSC 0
#define CFG_TUH_MIDI TINYUSB_HAS_MIDI_HOST
#define CFG_TUH_VENDOR 0
#define CFG_TUH_MIDI_STREAM_API TINYUSB_HAS_MIDI_HOST
#define CFG_TUH_MIDI_RX_BUFSIZE 512
#define CFG_TUH_MIDI_TX_BUFSIZE 512
#define CFG_TUH_MIDI_EP_BUFSIZE 64

#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_CDC 0
#define CFG_TUD_MSC 0
#define CFG_TUD_HID 0
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0

#else

#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUH_ENABLED 0
#define CFG_TUD_ENABLED 1

#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_CDC 0
#define CFG_TUD_MSC 0
#define CFG_TUD_HID 0
#define CFG_TUD_MIDI 1
#define CFG_TUD_VENDOR 0
#define CFG_TUD_MIDI_RX_BUFSIZE 512
#define CFG_TUD_MIDI_TX_BUFSIZE 512

#endif

#ifdef __cplusplus
}
#endif

#endif
